apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-role
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["catalogsources", "subscriptions", "installplans", "clusterserviceversions"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
