apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-role-binding
subjects:
  - kind: ServiceAccount
    name: pipeline # SA pipeline is created automatically
    namespace: pipeline-samples
roleRef:
  kind: ClusterRole
  name: pipeline-role
  apiGroup: rbac.authorization.k8s.io
